version: '3'

services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    hostname: dynamodblocal
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    working_dir: /home/dynamodblocal