
service: aws-golang-rest-api-with-dynamodb
app: aws-golang-rest-api-with-dynamodb

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  profile: AwsITC
  stage: dev
  region: us-east-1
  iam: # you can add statements to the Lambda function's IAM Role here
    role: arn:aws:iam::577230277200:role/lambda-api-dynamo-watch

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  test:
    handler: bin/main
    description: Serves API Gateway request
    package: 
      include: ./bin/main
    memorySize: 128
    timeout: 8
    events:
      - http:
          path: /test
          method: get
          cors: true

